jwt.secret=ahb456bfg6dfyr7638nnvgfhryt645gdbbfyrbjviw9847652wndhgdbr54562vcbfbb
spring.web.allowed-origins=http://localhost:5173
groq.api.key=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


